version: "3"
services:
  ###############################################################################
  # Mongo - Database
  ###############################################################################
  mongo:
    image: mongo
    container_name: autenticacao-mongo-db
    environment:
      MONGO_INITDB_DATABASE: cmi
      MONGO_INITDB_ROOT_USERNAME: mongocmi
      MONGO_INITDB_ROOT_PASSWORD: MongoCmi@123
      MONGO_INITDB_HOST: localhost
    tty: true
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - cmi-net

  ###############################################################################
  # Api - Node Aplication
  ###############################################################################
  cmi-autenticacao:
    image: cmi-autenticacao
    container_name: autenticacao-cmi
    expose:
      - 3000
    ports:
      - "3000:3000"
      - "9229:9229"
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run develop"
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      TZ: America/Sao_Paulo
      BD_URL: mongodb://localhost:27017/cmi
      BD_USER: mongocmi
      BD_PWD: MongoCmi@123
      API_PORT: 3000
      APP_HOST: "localhost:3000"
      CHART_VERSION: "1.0.0"
      LOG_LEVEL: "debug"
    tty: true
    restart: unless-stopped
    networks:
      - cmi-net

networks:
  cmi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24
