version: "3"
services:
  ###############################################################################
  # Mongo - Database
  ###############################################################################
  mongo:
    image: mongo
    container_name: passageiro-mongodb
    environment:
      MONGO_INITDB_URI: "mongodb+srv://mongocmi:n1E8DxRjR4INjLws@cmi.q6k96.mongodb.net/cmi"
    tty: true
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - cmi-passageiro-net

  ###############################################################################
  # Api - Node Aplication
  ###############################################################################
  cmi-fatura:
    image: cmi-fatura
    container_name: fatura
    expose:
      - 3007
    ports:
      - "3007:3007"
      - "9229:9229"
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "npm run develop"
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      TZ: America/Sao_Paulo
      BD_URI: "mongodb+srv://mongocmi:n1E8DxRjR4INjLws@cmi.q6k96.mongodb.net/cmi"
      API_PORT: 3007
      APP_HOST: "localhost:3007"
      CHART_VERSION: "1.0.0"
      LOG_LEVEL: "debug"
    tty: true
    restart: unless-stopped
    networks:
      - cmi-fatura-net

networks:
  cmi-fatura-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24
