version: "3"
services:
  ###############################################################################
  # Mongo - Database
  ###############################################################################
  mongo:
    image: mongo
    container_name: usuario-mongodb
    environment:
      MONGO_INITDB_URI: "mongodb+srv://mongocmi:n1E8DxRjR4INjLws@cmi.q6k96.mongodb.net/cmi"
    tty: true
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - cmi-usuario-net

  ###############################################################################
  # Api - Node Aplication
  ###############################################################################
  cmi-usuario:
    image: cmi-usuario
    container_name: usuario
    expose:
      - 3001
    ports:
      - "3001:3001"
      - "9229:9229"
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "npm run develop"
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      TZ: America/Sao_Paulo
      BD_URI: "mongodb+srv://mongocmi:n1E8DxRjR4INjLws@cmi.q6k96.mongodb.net/cmi"
      API_PORT: 3001
      APP_HOST: "localhost:3001"
      CHART_VERSION: "1.0.0"
      LOG_LEVEL: "debug"
      CMU_TERMO_DE_USO_HOST: "http://cmu-termo-de-uso:3008"
    tty: true
    restart: unless-stopped
    networks:
      - cmi-usuario-net

networks:
  cmi-usuario-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24
